#!/usr/bin/env bash
set -x -e

FONTSDIR=$HOME/.fonts
if [ ! -d "$FONTSDIR" ]; then
  mkdir $FONTSDIR
fi

INCONSOLATA=$FONTSDIR/Inconsolata-LGC
if [ ! -d "$INCONSOLATA/.git" ]; then
  git clone https://github.com/DeLaGuardo/Inconsolata-LGC.git $INCONSOLATA
fi

# Monaco font for windows can be found there: http://www.gringod.com/2006/11/01/new-version-of-monaco-font/
wget -O ~/.fonts/Monaco_Linux.ttf http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf

fc-cache -v
fc-list | egrep -wi --color "monaco|inconsolata"

